### ISSUE TITLE
Bloom filter crash

### ISSUE THREAD

**Issue by Krobys** [ackintosh/bloom-filter-kotlin#1]
when passing string inside (im not sure which one)

Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: arraycopy: length -29 is negative
	at java.base/java.lang.System.arraycopy(Native Method)
	at java.base/sun.security.provider.DigestBase.engineUpdate(DigestBase.java:118)
	at java.base/java.security.MessageDigest$Delegate.engineUpdate(MessageDigest.java:658)
	at java.base/java.security.MessageDigest.update(MessageDigest.java:359)
	at java.base/java.security.MessageDigest.digest(MessageDigest.java:434)
	at wallets_broot.address_checker.BloomFilter$Hash.call(BloomFilter.kt:40)
	at wallets_broot.address_checker.BloomFilter.contains(BloomFilter.kt:28)
	at wallets_broot.wallets.btc.UniversalAddressChecker.checkAddress(UniversalAddressChecker.kt:23)
	at wallets_broot.wallets.btc.legacy.BtcLegacyWalletType.checkAddress(BtcLegacyWalletType.kt:25)
	at wallets_broot.WalletChecker$launchTasksForMnemonics$2$1$1.invokeSuspend(WalletChecker.kt:81)

**Comment by Krobys** [comment]
I suspect the problem is related to how you concatenate inside md5.digest and what needs to be wrapped in byteArrayOf(seed.toByte())
